# Server
server.port=8080

# Enable JPA + Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Use Railway PostgreSQL (auto from env variable)
spring.datasource.url=${DATABASE_URL}
spring.datasource.driver-class-name=org.postgresql.Driver

# CORS
rainscape.cors.allowed-origins=*

# Security (You can remove later)
spring.security.user.name=admin
spring.security.user.password=secret123

# Prevent errors with SSL (Railway Postgres requires SSL)
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.maximum-pool-size=5
spring.sql.init.platform=postgres
spring.datasource.hikari.data-source-properties.ssl=true
spring.datasource.hikari.data-source-properties.sslmode=require
